[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/daisychain-contact"
  to = "/.netlify/functions/daisychain-contact"
  status = 200

[[redirects]]
  from = "/api/daisychain-action"
  to = "/.netlify/functions/daisychain-action"
  status = 200

[[redirects]]
  from = "/api/mobilize-events"
  to = "/.netlify/functions/mobilize-events"
  status = 200
